const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

/**
 * Product Seeder for Recommendation System Testing
 * 
 * This seeder creates 150 realistic products across Course, Book, and License
 * categories with varied ratings, review counts, and statuses.
 * 
 * Run with: npx prisma db seed --schema=prisma/schema.prisma
 * Or: node prisma/product-seed.js
 */

async function seedProducts() {
    console.log("🌱 Starting product seed for recommendation testing...");

    // Get existing seller IDs
    const techSeller = await prisma.user.findUnique({ where: { email: "seller@digistore.com" } });
    const bookSeller = await prisma.user.findUnique({ where: { email: "bookseller@digistore.com" } });

    if (!techSeller || !bookSeller) {
        console.error("❌ Please run the main seed.js first to create sellers.");
        process.exit(1);
    }

    const sellerMap = {
        'Course': techSeller.id,
        'Book': bookSeller.id,
        'License': techSeller.id,
    };

    const products = [
        {
            title: "React",
            description: "دوره جامع React با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 774000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-react",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.1,
            reviewCount: 8,
            allowSubscription: true
        },
        {
            title: "Next.js",
            description: "دوره جامع Next.js با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 678000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/nextjs",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 0.0,
            reviewCount: 0,
            allowSubscription: true
        },
        {
            title: "Vue.js",
            description: "دوره جامع Vue.js با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 637000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/vuejs",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 43,
            allowSubscription: true
        },
        {
            title: "Angular",
            description: "دوره جامع Angular با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 404000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-angular",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.1,
            reviewCount: 15,
            allowSubscription: true
        },
        {
            title: "Svelte",
            description: "دوره جامع Svelte با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 509000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/svelte-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 73,
            allowSubscription: true
        },
        {
            title: "Remix",
            description: "دوره جامع Remix با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 507000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/remix",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 61,
            allowSubscription: true
        },
        {
            title: "Gatsby",
            description: "دوره جامع Gatsby با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 841000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-gatsby",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 5.0,
            reviewCount: 89,
            allowSubscription: false
        },
        {
            title: "Astro",
            description: "Astro را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 509000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/astro-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.6,
            reviewCount: 41,
            allowSubscription: true
        },
        {
            title: "Node.js",
            description: "دوره جامع Node.js با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 838000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/nodejs",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.6,
            reviewCount: 74,
            allowSubscription: true
        },
        {
            title: "Express.js",
            description: "آموزش پیشرفته Express.js از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 775000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/expressjs",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 38,
            allowSubscription: false
        },
        {
            title: "NestJS",
            description: "NestJS را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 530000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-nestjs",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 5.0,
            reviewCount: 110,
            allowSubscription: true
        },
        {
            title: "Fastify",
            description: "مسترکلاس Fastify با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 631000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/fastify",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.1,
            reviewCount: 22,
            allowSubscription: true
        },
        {
            title: "Koa",
            description: "مسترکلاس Koa با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 718000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/koa",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.4,
            reviewCount: 21,
            allowSubscription: true
        },
        {
            title: "Hapi",
            description: "دوره جامع Hapi با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 168000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-hapi",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 46,
            allowSubscription: true
        },
        {
            title: "AdonisJS",
            description: "مسترکلاس AdonisJS با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 730000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/adonisjs",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 29,
            allowSubscription: true
        },
        {
            title: "Meteor",
            description: "Meteor را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 669000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/meteor",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.1,
            reviewCount: 5,
            allowSubscription: false
        },
        {
            title: "TypeScript",
            description: "آموزش پیشرفته TypeScript از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 389000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/typescript",
            status: "PENDING",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 193,
            allowSubscription: true
        },
        {
            title: "JavaScript Advanced",
            description: "آموزش پیشرفته JavaScript Advanced از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 323000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/javascript-advanced-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 15,
            allowSubscription: true
        },
        {
            title: "ES6+ Features",
            description: "دوره جامع ES6+ Features با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 620000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-es6+-features",
            status: "PENDING",
            sellerId: sellerMap["Course"],
            averageRating: 5.0,
            reviewCount: 108,
            allowSubscription: true
        },
        {
            title: "WebAssembly",
            description: "دوره جامع WebAssembly با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 366000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-webassembly",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 5.0,
            reviewCount: 166,
            allowSubscription: false
        },
        {
            title: "GraphQL",
            description: "مسترکلاس GraphQL با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 251000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/graphql",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 42,
            allowSubscription: false
        },
        {
            title: "REST API Design",
            description: "آموزش پیشرفته REST API Design از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 826000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/rest-api-design",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 142,
            allowSubscription: false
        },
        {
            title: "Micro-frontends",
            description: "دوره جامع Micro-frontends با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 582000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-micro-frontends",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.2,
            reviewCount: 12,
            allowSubscription: true
        },
        {
            title: "Progressive Web Apps",
            description: "دوره جامع Progressive Web Apps با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 127000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/progressive-web-apps",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.4,
            reviewCount: 15,
            allowSubscription: true
        },
        {
            title: "Flutter",
            description: "Flutter را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 363000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/flutter",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 75,
            allowSubscription: true
        },
        {
            title: "React Native",
            description: "مسترکلاس React Native با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 604000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-react-native",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.6,
            reviewCount: 67,
            allowSubscription: true
        },
        {
            title: "Swift UI",
            description: "دوره جامع Swift UI با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 175000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-swift-ui",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.3,
            reviewCount: 12,
            allowSubscription: true
        },
        {
            title: "Kotlin Multiplatform",
            description: "مسترکلاس Kotlin Multiplatform با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 669000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-kotlin-multiplatform",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.1,
            reviewCount: 7,
            allowSubscription: true
        },
        {
            title: "Ionic",
            description: "دوره جامع Ionic با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 683000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-ionic",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.5,
            reviewCount: 26,
            allowSubscription: false
        },
        {
            title: "Capacitor",
            description: "آموزش پیشرفته Capacitor از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 362000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/capacitor-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.2,
            reviewCount: 6,
            allowSubscription: true
        },
        {
            title: "NativeScript",
            description: "مسترکلاس NativeScript با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 122000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/nativescript-playlist",
            status: "PENDING",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 172,
            allowSubscription: true
        },
        {
            title: "Expo",
            description: "آموزش پیشرفته Expo از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 618000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-expo",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 168,
            allowSubscription: true
        },
        {
            title: "iOS Development",
            description: "دوره جامع iOS Development با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 441000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-ios-development",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 35,
            allowSubscription: true
        },
        {
            title: "Android Development",
            description: "دوره جامع Android Development با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 640000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-android-development",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 3.8,
            reviewCount: 7,
            allowSubscription: true
        },
        {
            title: "Cross-platform Architecture",
            description: "آموزش پیشرفته Cross-platform Architecture از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 703000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/cross-platform-architecture",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.6,
            reviewCount: 55,
            allowSubscription: false
        },
        {
            title: "Mobile UX Design",
            description: "Mobile UX Design را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 329000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-mobile-ux-design",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 3.6,
            reviewCount: 8,
            allowSubscription: true
        },
        {
            title: "App Store Optimization",
            description: "دوره جامع App Store Optimization با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 194000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/app-store-optimization-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.5,
            reviewCount: 42,
            allowSubscription: true
        },
        {
            title: "Mobile Security",
            description: "Mobile Security را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 255000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-mobile-security",
            status: "PENDING",
            sellerId: sellerMap["Course"],
            averageRating: 4.5,
            reviewCount: 53,
            allowSubscription: true
        },
        {
            title: "Push Notifications",
            description: "دوره جامع Push Notifications با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 789000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/push-notifications",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.3,
            reviewCount: 9,
            allowSubscription: true
        },
        {
            title: "Offline-first Mobile",
            description: "آموزش پیشرفته Offline-first Mobile از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 229000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/offline-first-mobile-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.1,
            reviewCount: 25,
            allowSubscription: false
        },
        {
            title: "Python for Data Science",
            description: "مسترکلاس Python for Data Science با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 637000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/python-for-data-science-playlist",
            status: "PENDING",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 138,
            allowSubscription: false
        },
        {
            title: "Machine Learning Basics",
            description: "دوره جامع Machine Learning Basics با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 165000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/machine-learning-basics-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.6,
            reviewCount: 71,
            allowSubscription: true
        },
        {
            title: "Deep Learning with PyTorch",
            description: "دوره جامع Deep Learning with PyTorch با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 557000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-deep-learning-with-pytorch",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 5.0,
            reviewCount: 169,
            allowSubscription: true
        },
        {
            title: "TensorFlow Mastery",
            description: "آموزش پیشرفته TensorFlow Mastery از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 498000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/tensorflow-mastery-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.4,
            reviewCount: 6,
            allowSubscription: false
        },
        {
            title: "NLP with Python",
            description: "آموزش پیشرفته NLP with Python از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 335000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/nlp-with-python",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 5.0,
            reviewCount: 134,
            allowSubscription: false
        },
        {
            title: "Computer Vision",
            description: "آموزش پیشرفته Computer Vision از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 278000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-computer-vision",
            status: "REJECTED",
            sellerId: sellerMap["Course"],
            averageRating: 5.0,
            reviewCount: 36,
            allowSubscription: true
        },
        {
            title: "Time Series Analysis",
            description: "مسترکلاس Time Series Analysis با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 460000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/time-series-analysis",
            status: "PENDING",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 57,
            allowSubscription: true
        },
        {
            title: "Reinforcement Learning",
            description: "مسترکلاس Reinforcement Learning با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 159000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-reinforcement-learning",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 88,
            allowSubscription: true
        },
        {
            title: "Data Visualization",
            description: "آموزش پیشرفته Data Visualization از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 795000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/data-visualization-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 5.0,
            reviewCount: 101,
            allowSubscription: true
        },
        {
            title: "Statistical Analysis",
            description: "مسترکلاس Statistical Analysis با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 641000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/statistical-analysis",
            status: "REJECTED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 29,
            allowSubscription: false
        },
        {
            title: "Big Data with Spark",
            description: "آموزش پیشرفته Big Data with Spark از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 387000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/big-data-with-spark",
            status: "REJECTED",
            sellerId: sellerMap["Course"],
            averageRating: 4.0,
            reviewCount: 18,
            allowSubscription: true
        },
        {
            title: "MLOps",
            description: "مسترکلاس MLOps با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 441000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/mlops",
            status: "REJECTED",
            sellerId: sellerMap["Course"],
            averageRating: 3.8,
            reviewCount: 4,
            allowSubscription: true
        },
        {
            title: "Feature Engineering",
            description: "مسترکلاس Feature Engineering با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 845000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-feature-engineering",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 80,
            allowSubscription: true
        },
        {
            title: "Model Deployment",
            description: "Model Deployment را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 191000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/model-deployment",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 106,
            allowSubscription: true
        },
        {
            title: "Data Cleaning",
            description: "مسترکلاس Data Cleaning با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 802000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/data-cleaning-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.1,
            reviewCount: 18,
            allowSubscription: true
        },
        {
            title: "A/B Testing",
            description: "آموزش پیشرفته A/B Testing از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 508000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/a/b-testing",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 53,
            allowSubscription: true
        },
        {
            title: "Docker & Kubernetes",
            description: "Docker & Kubernetes را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 560000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/docker-&-kubernetes-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 36,
            allowSubscription: true
        },
        {
            title: "AWS Solutions Architect",
            description: "AWS Solutions Architect را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 410000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-aws-solutions-architect",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 87,
            allowSubscription: false
        },
        {
            title: "Azure Fundamentals",
            description: "دوره جامع Azure Fundamentals با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 270000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-azure-fundamentals",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 24,
            allowSubscription: true
        },
        {
            title: "GCP Professional",
            description: "آموزش پیشرفته GCP Professional از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 764000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/gcp-professional",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.6,
            reviewCount: 15,
            allowSubscription: false
        },
        {
            title: "CI/CD Pipelines",
            description: "مسترکلاس CI/CD Pipelines با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 229000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-ci/cd-pipelines",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 42,
            allowSubscription: true
        },
        {
            title: "Infrastructure as Code",
            description: "مسترکلاس Infrastructure as Code با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 244000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-infrastructure-as-code",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 55,
            allowSubscription: false
        },
        {
            title: "Monitoring & Logging",
            description: "مسترکلاس Monitoring & Logging با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 573000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/monitoring-&-logging",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.3,
            reviewCount: 19,
            allowSubscription: true
        },
        {
            title: "Site Reliability Engineering",
            description: "Site Reliability Engineering را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 373000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/site-reliability-engineering",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.2,
            reviewCount: 14,
            allowSubscription: true
        },
        {
            title: "Terraform",
            description: "Terraform را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 463000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/terraform",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.2,
            reviewCount: 9,
            allowSubscription: true
        },
        {
            title: "Ansible",
            description: "مسترکلاس Ansible با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 185000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/ansible-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.5,
            reviewCount: 68,
            allowSubscription: true
        },
        {
            title: "Jenkins",
            description: "دوره جامع Jenkins با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 718000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/jenkins",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 0.0,
            reviewCount: 0,
            allowSubscription: true
        },
        {
            title: "GitHub Actions",
            description: "مسترکلاس GitHub Actions با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 519000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/github-actions",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 43,
            allowSubscription: true
        },
        {
            title: "ArgoCD",
            description: "مسترکلاس ArgoCD با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 399000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/argocd-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.3,
            reviewCount: 17,
            allowSubscription: true
        },
        {
            title: "Prometheus & Grafana",
            description: "آموزش پیشرفته Prometheus & Grafana از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 598000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/prometheus-&-grafana",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 199,
            allowSubscription: true
        },
        {
            title: "ELK Stack",
            description: "مسترکلاس ELK Stack با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 778000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-elk-stack",
            status: "PENDING",
            sellerId: sellerMap["Course"],
            averageRating: 4.1,
            reviewCount: 15,
            allowSubscription: true
        },
        {
            title: "Service Mesh",
            description: "Service Mesh را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 454000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/service-mesh-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 50,
            allowSubscription: true
        },
        {
            title: "Ethical Hacking",
            description: "دوره جامع Ethical Hacking با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 672000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/ethical-hacking-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 3.9,
            reviewCount: 1,
            allowSubscription: false
        },
        {
            title: "Penetration Testing",
            description: "آموزش پیشرفته Penetration Testing از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 373000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-penetration-testing",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.2,
            reviewCount: 8,
            allowSubscription: true
        },
        {
            title: "Network Security",
            description: "مسترکلاس Network Security با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 343000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/network-security",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 29,
            allowSubscription: false
        },
        {
            title: "Web App Security",
            description: "Web App Security را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 287000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-web-app-security",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 126,
            allowSubscription: true
        },
        {
            title: "Cryptography",
            description: "دوره جامع Cryptography با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 323000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/cryptography",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.5,
            reviewCount: 53,
            allowSubscription: false
        },
        {
            title: "Digital Forensics",
            description: "دوره جامع Digital Forensics با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 734000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/digital-forensics",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.2,
            reviewCount: 16,
            allowSubscription: true
        },
        {
            title: "SOC Analyst",
            description: "SOC Analyst را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 783000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-soc-analyst",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 122,
            allowSubscription: true
        },
        {
            title: "Cloud Security",
            description: "آموزش پیشرفته Cloud Security از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 590000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/cloud-security-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 76,
            allowSubscription: true
        },
        {
            title: "OSCP Preparation",
            description: "OSCP Preparation را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 726000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/oscp-preparation-playlist",
            status: "PENDING",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 145,
            allowSubscription: true
        },
        {
            title: "Bug Bounty Hunting",
            description: "مسترکلاس Bug Bounty Hunting با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 595000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/bug-bounty-hunting-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.8,
            reviewCount: 84,
            allowSubscription: true
        },
        {
            title: "Malware Analysis",
            description: "Malware Analysis را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 384000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/malware-analysis-playlist",
            status: "PENDING",
            sellerId: sellerMap["Course"],
            averageRating: 4.9,
            reviewCount: 32,
            allowSubscription: true
        },
        {
            title: "Reverse Engineering",
            description: "دوره جامع Reverse Engineering با پروژه‌های عملی و مدرک معتبر. مناسب برای افرادی که می‌خواهند در کوتاه‌ترین زمان به سطح حرفه‌ای برسند.",
            price: 315000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-reverse-engineering",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 75,
            allowSubscription: true
        },
        {
            title: "Security Architecture",
            description: "مسترکلاس Security Architecture با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 622000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-security-architecture",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.3,
            reviewCount: 14,
            allowSubscription: true
        },
        {
            title: "Identity Management",
            description: "مسترکلاس Identity Management با اساتید برتر صنعت. پروژه‌محور، کاربردی و به‌روز با آخرین تکنولوژی‌ها.",
            price: 497000,
            category: "Course",
            fileUrl: "https://cdn.digistore.app/streams/identity-management",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 57,
            allowSubscription: true
        },
        {
            title: "Threat Intelligence",
            description: "Threat Intelligence را از صفر تا صد یاد بگیرید. این دوره شامل ویدیوهای HD، فایل‌های تمرینی و جامعه تخصصی است.",
            price: 584000,
            category: "Course",
            fileUrl: "https://videos.digistore.ir/threat-intelligence-playlist",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 3.2,
            reviewCount: 2,
            allowSubscription: true
        },
        {
            title: "Incident Response",
            description: "آموزش پیشرفته Incident Response از مبتدی تا پیشرفته. شامل تمرین‌های کدنویسی، پروژه نهایی و پشتیبانی مادام‌العمر.",
            price: 826000,
            category: "Course",
            fileUrl: "https://stream.digistore.com/course-incident-response",
            status: "APPROVED",
            sellerId: sellerMap["Course"],
            averageRating: 4.7,
            reviewCount: 51,
            allowSubscription: false
        },
        {
            title: "Clean Code",
            description: "نسخه دیجیتال کتاب Clean Code با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 74000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/clean-code.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.3,
            reviewCount: 9,
            allowSubscription: false
        },
        {
            title: "Design Patterns",
            description: "کتاب Design Patterns - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 95000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/design-patterns.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.5,
            reviewCount: 77,
            allowSubscription: false
        },
        {
            title: "Refactoring",
            description: "کتاب Refactoring - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 51000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/refactoring.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.6,
            reviewCount: 21,
            allowSubscription: false
        },
        {
            title: "The Pragmatic Programmer",
            description: "The Pragmatic Programmer - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 89000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/the-pragmatic-programmer.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.5,
            reviewCount: 21,
            allowSubscription: false
        },
        {
            title: "Code Complete",
            description: "Code Complete - راهنمای کامل و جامع. شامل مثال‌های کاربردی، نمودارها و تمرین‌های فصل به فصل.",
            price: 63000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/code-complete.zip",
            status: "PENDING",
            sellerId: sellerMap["Book"],
            averageRating: 3.2,
            reviewCount: 7,
            allowSubscription: false
        },
        {
            title: "Working Effectively with Legacy Code",
            description: "Working Effectively with Legacy Code - راهنمای کامل و جامع. شامل مثال‌های کاربردی، نمودارها و تمرین‌های فصل به فصل.",
            price: 180000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/working-effectively-with-legacy-code.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.9,
            reviewCount: 180,
            allowSubscription: false
        },
        {
            title: "Domain-Driven Design",
            description: "نسخه دیجیتال کتاب Domain-Driven Design با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 134000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/domain-driven-design.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.7,
            reviewCount: 41,
            allowSubscription: false
        },
        {
            title: "Building Microservices",
            description: "نسخه دیجیتال کتاب Building Microservices با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 79000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/building-microservices.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.2,
            reviewCount: 10,
            allowSubscription: false
        },
        {
            title: "Head First Design Patterns",
            description: "Head First Design Patterns - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 25000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/head-first-design-patterns.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.5,
            reviewCount: 51,
            allowSubscription: false
        },
        {
            title: "Patterns of Enterprise Architecture",
            description: "Patterns of Enterprise Architecture - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 97000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/patterns-of-enterprise-architecture.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 5.0,
            reviewCount: 190,
            allowSubscription: false
        },
        {
            title: "Software Architecture in Practice",
            description: "Software Architecture in Practice - راهنمای کامل و جامع. شامل مثال‌های کاربردی، نمودارها و تمرین‌های فصل به فصل.",
            price: 175000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/software-architecture-in-practice.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.1,
            reviewCount: 13,
            allowSubscription: false
        },
        {
            title: "Building Evolutionary Architectures",
            description: "کتاب Building Evolutionary Architectures - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 61000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/building-evolutionary-architectures.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.3,
            reviewCount: 23,
            allowSubscription: false
        },
        {
            title: "Fundamentals of Software Architecture",
            description: "Fundamentals of Software Architecture - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 98000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/fundamentals-of-software-architecture.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.2,
            reviewCount: 13,
            allowSubscription: false
        },
        {
            title: "Software Architecture: The Hard Parts",
            description: "Software Architecture: The Hard Parts - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 153000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/software-architecture:-the-hard-parts.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 0.0,
            reviewCount: 0,
            allowSubscription: false
        },
        {
            title: "Designing Data-Intensive Applications",
            description: "نسخه دیجیتال کتاب Designing Data-Intensive Applications با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 135000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/designing-data-intensive-applications.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 3.9,
            reviewCount: 1,
            allowSubscription: false
        },
        {
            title: "System Design Interview",
            description: "کتاب System Design Interview - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 93000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/system-design-interview.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.8,
            reviewCount: 38,
            allowSubscription: false
        },
        {
            title: "Introduction to Algorithms",
            description: "Introduction to Algorithms - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 174000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/introduction-to-algorithms.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.9,
            reviewCount: 134,
            allowSubscription: false
        },
        {
            title: "Algorithm Design Manual",
            description: "نسخه دیجیتال کتاب Algorithm Design Manual با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 110000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/algorithm-design-manual.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.2,
            reviewCount: 20,
            allowSubscription: false
        },
        {
            title: "Grokking Algorithms",
            description: "Grokking Algorithms - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 98000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/grokking-algorithms.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 3.2,
            reviewCount: 2,
            allowSubscription: false
        },
        {
            title: "Algorithms in C",
            description: "کتاب Algorithms in C - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 128000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/algorithms-in-c.zip",
            status: "PENDING",
            sellerId: sellerMap["Book"],
            averageRating: 4.5,
            reviewCount: 61,
            allowSubscription: false
        },
        {
            title: "Data Structures and Algorithms in Java",
            description: "Data Structures and Algorithms in Java - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 152000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/data-structures-and-algorithms-in-java.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.8,
            reviewCount: 71,
            allowSubscription: false
        },
        {
            title: "Competitive Programming",
            description: "کتاب Competitive Programming - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 149000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/competitive-programming.pdf",
            status: "REJECTED",
            sellerId: sellerMap["Book"],
            averageRating: 4.6,
            reviewCount: 35,
            allowSubscription: false
        },
        {
            title: "Algorithmic Thinking",
            description: "کتاب Algorithmic Thinking - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 104000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/algorithmic-thinking.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.3,
            reviewCount: 8,
            allowSubscription: false
        },
        {
            title: "Advanced Data Structures",
            description: "کتاب Advanced Data Structures - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 143000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/advanced-data-structures.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.7,
            reviewCount: 80,
            allowSubscription: false
        },
        {
            title: "Operating Systems Concepts",
            description: "Operating Systems Concepts - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 94000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/operating-systems-concepts.epub",
            status: "REJECTED",
            sellerId: sellerMap["Book"],
            averageRating: 4.2,
            reviewCount: 17,
            allowSubscription: false
        },
        {
            title: "Computer Networking",
            description: "Computer Networking - راهنمای کامل و جامع. شامل مثال‌های کاربردی، نمودارها و تمرین‌های فصل به فصل.",
            price: 73000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/computer-networking.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.9,
            reviewCount: 159,
            allowSubscription: false
        },
        {
            title: "Database Internals",
            description: "کتاب Database Internals - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 93000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/database-internals.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.9,
            reviewCount: 198,
            allowSubscription: false
        },
        {
            title: "Computer Architecture",
            description: "Computer Architecture - راهنمای کامل و جامع. شامل مثال‌های کاربردی، نمودارها و تمرین‌های فصل به فصل.",
            price: 150000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/computer-architecture.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.2,
            reviewCount: 22,
            allowSubscription: false
        },
        {
            title: "Distributed Systems",
            description: "Distributed Systems - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 121000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/distributed-systems.epub",
            status: "PENDING",
            sellerId: sellerMap["Book"],
            averageRating: 4.8,
            reviewCount: 128,
            allowSubscription: false
        },
        {
            title: "Concurrency in Go",
            description: "Concurrency in Go - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 84000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/concurrency-in-go.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.8,
            reviewCount: 63,
            allowSubscription: false
        },
        {
            title: "Programming Language Pragmatics",
            description: "Programming Language Pragmatics - راهنمای کامل و جامع. شامل مثال‌های کاربردی، نمودارها و تمرین‌های فصل به فصل.",
            price: 123000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/programming-language-pragmatics.epub",
            status: "REJECTED",
            sellerId: sellerMap["Book"],
            averageRating: 3.9,
            reviewCount: 6,
            allowSubscription: false
        },
        {
            title: "Compiler Design",
            description: "Compiler Design - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 50000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/compiler-design.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.7,
            reviewCount: 67,
            allowSubscription: false
        },
        {
            title: "The Clean Coder",
            description: "کتاب The Clean Coder - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 64000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/the-clean-coder.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.2,
            reviewCount: 17,
            allowSubscription: false
        },
        {
            title: "Soft Skills for Developers",
            description: "نسخه دیجیتال کتاب Soft Skills for Developers با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 45000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/soft-skills-for-developers.zip",
            status: "PENDING",
            sellerId: sellerMap["Book"],
            averageRating: 4.6,
            reviewCount: 77,
            allowSubscription: false
        },
        {
            title: "Cracking the Coding Interview",
            description: "کتاب Cracking the Coding Interview - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 163000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/cracking-the-coding-interview.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.8,
            reviewCount: 44,
            allowSubscription: false
        },
        {
            title: "System Design Interview Vol 2",
            description: "System Design Interview Vol 2 - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 48000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/system-design-interview-vol-2.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.8,
            reviewCount: 72,
            allowSubscription: false
        },
        {
            title: "The Manager Path",
            description: "کتاب The Manager Path - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 101000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/the-manager-path.pdf",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 3.3,
            reviewCount: 7,
            allowSubscription: false
        },
        {
            title: "Staff Engineer",
            description: "Staff Engineer - راهنمای کامل و جامع. شامل مثال‌های کاربردی، نمودارها و تمرین‌های فصل به فصل.",
            price: 62000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/staff-engineer.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.6,
            reviewCount: 37,
            allowSubscription: false
        },
        {
            title: "An Elegant Puzzle",
            description: "An Elegant Puzzle - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 45000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/an-elegant-puzzle.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.7,
            reviewCount: 44,
            allowSubscription: false
        },
        {
            title: "The Phoenix Project",
            description: "نسخه دیجیتال کتاب The Phoenix Project با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 143000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/the-phoenix-project.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 0.0,
            reviewCount: 0,
            allowSubscription: false
        },
        {
            title: "Team Topologies",
            description: "نسخه دیجیتال کتاب Team Topologies با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 144000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/team-topologies.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 3.9,
            reviewCount: 5,
            allowSubscription: false
        },
        {
            title: "Accelerate",
            description: "نسخه دیجیتال کتاب Accelerate با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 133000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/accelerate.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.2,
            reviewCount: 20,
            allowSubscription: false
        },
        {
            title: "Continuous Delivery",
            description: "Continuous Delivery - راهنمای کامل و جامع. شامل مثال‌های کاربردی، نمودارها و تمرین‌های فصل به فصل.",
            price: 52000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/continuous-delivery.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.8,
            reviewCount: 52,
            allowSubscription: false
        },
        {
            title: "The DevOps Handbook",
            description: "The DevOps Handbook - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 30000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/the-devops-handbook.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 5.0,
            reviewCount: 42,
            allowSubscription: false
        },
        {
            title: "Lean Software Development",
            description: "Lean Software Development - اثر کلاسیک حوزه نرم‌افزار. نسخه کامل بدون سانسور با تمام پیوست‌ها.",
            price: 180000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/lean-software-development.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.3,
            reviewCount: 12,
            allowSubscription: false
        },
        {
            title: "Extreme Programming Explained",
            description: "نسخه دیجیتال کتاب Extreme Programming Explained با قابلیت جستجو و یادداشت‌برداری. ترجمه فارسی روان و دقیق.",
            price: 73000,
            category: "Book",
            fileUrl: "https://cdn.digistore.app/downloads/extreme-programming-explained.zip",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 4.9,
            reviewCount: 65,
            allowSubscription: false
        },
        {
            title: "Scrum Guide",
            description: "کتاب Scrum Guide - نسخه PDF اورجینال با کیفیت چاپی. منبعی ضروری برای هر توسعه‌دهنده حرفه‌ای.",
            price: 49000,
            category: "Book",
            fileUrl: "https://files.digistore.ir/digital/scrum-guide.epub",
            status: "APPROVED",
            sellerId: sellerMap["Book"],
            averageRating: 0.0,
            reviewCount: 0,
            allowSubscription: false
        },
        {
            title: "Kanban",
            description: "Kanban - راهنمای کامل و جامع. شامل مثال‌های کاربردی، نمودارها و تمرین‌های فصل به فصل.",
            price: 118000,
            category: "Book",
            fileUrl: "https://storage.digistore.com/books/kanban.pdf",
            status: "PENDING",
            sellerId: sellerMap["Book"],
            averageRating: 4.2,
            reviewCount: 11,
            allowSubscription: false
        },
        {
            title: "JetBrains All Products Pack",
            description: "کلید فعال‌سازی JetBrains All Products Pack با بهترین قیمت بازار. تحویل فوری پس از پرداخت.",
            price: 691000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 5.0,
            reviewCount: 95,
            allowSubscription: false
        },
        {
            title: "IntelliJ IDEA Ultimate",
            description: "کلید فعال‌سازی IntelliJ IDEA Ultimate با بهترین قیمت بازار. تحویل فوری پس از پرداخت.",
            price: 2120000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 4.0,
            reviewCount: 7,
            allowSubscription: false
        },
        {
            title: "WebStorm License",
            description: "WebStorm License - لایسنس lifetime با آپدیت رایگان. اورجینال ۱۰۰٪ و قابل استفاده در محیط تجاری.",
            price: 726000,
            category: "License",
            fileUrl: "",
            status: "PENDING",
            sellerId: sellerMap["License"],
            averageRating: 5.0,
            reviewCount: 172,
            allowSubscription: false
        },
        {
            title: "PyCharm Professional",
            description: "لایسنس اصلی و قانونی PyCharm Professional با ضمانت فعال‌سازی. تحویل آنی و پشتیبانی ۲۴ ساعته.",
            price: 1650000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 0.0,
            reviewCount: 0,
            allowSubscription: false
        },
        {
            title: "VS Code Pro (GitHub Copilot)",
            description: "لایسنس اصلی و قانونی VS Code Pro (GitHub Copilot) با ضمانت فعال‌سازی. تحویل آنی و پشتیبانی ۲۴ ساعته.",
            price: 2350000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 4.7,
            reviewCount: 63,
            allowSubscription: false
        },
        {
            title: "Cursor AI Editor",
            description: "لایسنس اصلی و قانونی Cursor AI Editor با ضمانت فعال‌سازی. تحویل آنی و پشتیبانی ۲۴ ساعته.",
            price: 1670000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 4.7,
            reviewCount: 56,
            allowSubscription: false
        },
        {
            title: "Sublime Text License",
            description: "لایسنس اصلی و قانونی Sublime Text License با ضمانت فعال‌سازی. تحویل آنی و پشتیبانی ۲۴ ساعته.",
            price: 1060000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 4.7,
            reviewCount: 67,
            allowSubscription: false
        },
        {
            title: "Nova Editor for Mac",
            description: "Nova Editor for Mac - لایسنس lifetime با آپدیت رایگان. اورجینال ۱۰۰٪ و قابل استفاده در محیط تجاری.",
            price: 627000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 0.0,
            reviewCount: 0,
            allowSubscription: false
        },
        {
            title: "Docker Desktop Pro",
            description: "لایسنس اصلی و قانونی Docker Desktop Pro با ضمانت فعال‌سازی. تحویل آنی و پشتیبانی ۲۴ ساعته.",
            price: 2170000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 4.8,
            reviewCount: 146,
            allowSubscription: false
        },
        {
            title: "GitKraken Pro",
            description: "اشتراک GitKraken Pro برای تیم‌های توسعه. مدیریت لایسنس از طریق پنل اختصاصی.",
            price: 1670000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 5.0,
            reviewCount: 197,
            allowSubscription: false
        },
        {
            title: "Tower Git Client",
            description: "اشتراک Tower Git Client برای تیم‌های توسعه. مدیریت لایسنس از طریق پنل اختصاصی.",
            price: 555000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 4.9,
            reviewCount: 124,
            allowSubscription: false
        },
        {
            title: "SourceTree Pro",
            description: "اشتراک SourceTree Pro برای تیم‌های توسعه. مدیریت لایسنس از طریق پنل اختصاصی.",
            price: 1040000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 4.1,
            reviewCount: 16,
            allowSubscription: false
        },
        {
            title: "Postman Team",
            description: "کلید فعال‌سازی Postman Team با بهترین قیمت بازار. تحویل فوری پس از پرداخت.",
            price: 2380000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 4.4,
            reviewCount: 19,
            allowSubscription: false
        },
        {
            title: "Insomnia Plus",
            description: "Insomnia Plus - لایسنس lifetime با آپدیت رایگان. اورجینال ۱۰۰٪ و قابل استفاده در محیط تجاری.",
            price: 525000,
            category: "License",
            fileUrl: "",
            status: "APPROVED",
            sellerId: sellerMap["License"],
            averageRating: 4.5,
            reviewCount: 57,
            allowSubscription: false
        }
    ];

    let created = 0;
    let skipped = 0;

    for (const productData of products) {
        // Skip if product with same title already exists
        const existing = await prisma.product.findFirst({
            where: { title: productData.title }
        });

        if (existing) {
            skipped++;
            continue;
        }

        await prisma.product.create({ data: productData });
        created++;
    }

    console.log(`✅ Product seed complete! Created: ${created}, Skipped (already exist): ${skipped}`);
    console.log(`📊 Total products in database: ${await prisma.product.count()}`);
}

// Standalone execution
if (require.main === module) {
    seedProducts()
        .catch((e) => {
            console.error("❌ Product seed failed:", e);
            process.exit(1);
        })
        .finally(async () => {
            await prisma.$disconnect();
        });
}

module.exports = { seedProducts };
